---
name: Registry Testing

on:
  workflow_dispatch:
    inputs:
      rancher_version:
        description: "Rancher version"
      rancher_chart_version:
        description: "Rancher chart version"
      run_all_versions:
        description: "Run all supported versions if manually triggered"
        required: false
        default: false
        type: boolean
  workflow_call:
    inputs:
      rancher_version:
        description: "Rancher tag version provided from check-rancher-tag workflow"
        required: true
        type: string
      rancher_chart_version:
        description: "Rancher chart version provided from check-rancher-chart-version workflow"
        required: true
        type: string

env:
  CLOUD_PROVIDER_VERSION: "5.95.0"
  HOSTNAME_PREFIX: tfp-registry
  LOCALS_PROVIDER_VERSION: "${{ vars.LOCALS_PROVIDER_VERSION }}"
  PACKAGE: registries
  RKE_PROVIDER_VERSION: "${{ vars.RKE_PROVIDER_VERSION }}"
  TEST_SUITE: ^TestTfpRegistriesTestSuite$
  SUITE_TIMEOUT: 7h

permissions:
  id-token: write
  contents: read

jobs:
  registry-tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: v2-12
            environment: alpha
            provider_version: ${{ vars.RANCHER2_PROVIDER_VERSION_2_12 }}
            rke2_version: ${{ vars.RKE2_VERSION_2_12 }}
            rancher_chart_version: ${{ vars.RELEASED_RANCHER_CHART_VERSION_2_12 }}
            rancher_version: ${{ vars.RANCHER_VERSION_2_12_HEAD }}
            qase_id: ${{ vars.QASE_RECURRING_TEST_RUN_ID_2_12 }}

          - version: v2-11
            environment: staging-alpha
            provider_version: ${{ vars.RANCHER2_PROVIDER_VERSION_2_11 }}
            rke2_version: ${{ vars.RKE2_VERSION_2_11 }}
            rancher_chart_version: ${{ vars.RELEASED_RANCHER_CHART_VERSION_2_11 }}
            rancher_version: ${{ vars.RANCHER_VERSION_2_11_HEAD }}
            qase_id: ${{ vars.QASE_RECURRING_TEST_RUN_ID_2_11 }}
    name: ${{ matrix.version }}
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
    env:
      RANCHER2_PROVIDER_VERSION: ${{ matrix.provider_version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Skip if not needed (v2-12)
        if: ${{ matrix.version == 'v2-12' }}
        run: |
          if [[ "${{ github.event.inputs.run_all_versions }}" == "true" ]]; then
            echo "Running v2-12 job"
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.rancher_version }}" == "v2.12.*" && "${{ github.event.inputs.rancher_version }}" == *-alpha* ]]; then
            echo "Running v2-12 job"
          elif [[ "${{ github.event_name }}" == "workflow_call" && "${{ inputs.rancher_version }}" == "v2.12.*" && "${{ inputs.rancher_version }}" == *-alpha* ]]; then
            echo "Running v2-12 job"
          else
            echo "Skipping v2-12 job"
            exit 0
          fi

      - name: Skip if not needed (v2-11)
        if: ${{ matrix.version == 'v2-11' }}
        run: |
          if [[ "${{ github.event.inputs.run_all_versions }}" == "true" ]]; then
            echo "Running v2-11 job"
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.rancher_version }}" == v2.11.* && "${{ github.event.inputs.rancher_version }}" == *-alpha* ]]; then
            echo "Running v2-11 job"
          elif [[ "${{ github.event_name }}" == "workflow_call" && "${{ inputs.rancher_version }}" == v2.11.* && "${{ inputs.rancher_version }}" == *-alpha* ]]; then
            echo "Running v2-11 job"
          else
            echo "Skipping v2-11 job"
            exit 0
          fi

      - name: Set up environment variables
        run: |
          if [ "${{ matrix.environment }}" == "alpha" ]; then
            echo "PREFIX_LIST_ID=${{ secrets.AWS_MANAGED_PREFIX_LIST_ID }}" >> $GITHUB_ENV
            echo "SECURITY_GROUPS=${{ secrets.AWS_SECURITY_GROUPS }}" >> $GITHUB_ENV
            echo "SECURITY_GROUP_NAMES=${{ secrets.AWS_SECURITY_GROUP_NAMES }}" >> $GITHUB_ENV
            echo "RANCHER_AGENT_IMAGE=" >> $GITHUB_ENV
          elif [ "${{ matrix.environment }}" == "staging-alpha" ]; then
            echo "PREFIX_LIST_ID=${{ secrets.AWS_MANAGED_PREFIX_LIST_ID_PRIME }}" >> $GITHUB_ENV
            echo "SECURITY_GROUPS=${{ secrets.AWS_SECURITY_GROUPS_PRIME }}" >> $GITHUB_ENV
            echo "SECURITY_GROUP_NAMES=${{ secrets.AWS_SECURITY_GROUP_NAMES_PRIME }}" >> $GITHUB_ENV
            echo "RANCHER_AGENT_IMAGE=${{ secrets.RANCHER_AGENT_IMAGE }}" >> $GITHUB_ENV
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.TFP_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get AWS credentials from Secrets Manager
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            AWS_ACCESS_KEY, ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_KEY, ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: "Fetch and Set DockerHub Credentials"
        uses: rancher-eio/read-vault-secrets@main
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/dockerhub/org-token/credentials username | DOCKERHUB_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/dockerhub/org-token/credentials password | DOCKERHUB_PASSWORD

      - name: Mask Dockerhub Credentials
        run: |
          echo "::add-mask::${{ env.DOCKERHUB_USERNAME }}"
          echo "::add-mask::${{ env.DOCKERHUB_PASSWORD }}"

      - name: Whitelist Runner IP
        uses: ./.github/actions/whitelist-runner-ip
        with:
          prefix-list-id: ${{ env.PREFIX_LIST_ID }}
          region: "${{ secrets.AWS_REGION }}"

      - name: Set up SSH Keys
        uses: ./.github/actions/setup-ssh-keys
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-private-key-name: ${{ secrets.SSH_PRIVATE_KEY_NAME }}
          windows-ssh-private-key: ${{ secrets.WINDOWS_SSH_PRIVATE_KEY }}
          windows-ssh-private-key-name: ${{ secrets.WINDOWS_SSH_PRIVATE_KEY_NAME }}

      - name: Uniquify hostname prefix
        uses: ./.github/actions/uniquify-hostname

      - name: Set Rancher version
        uses: ./.github/actions/set-env-var
        with:
          key: RANCHER_VERSION
          value: | 
            ${{ 
              github.event.inputs.rancher_version || 
              (github.event_name == 'workflow_dispatch' && matrix.rancher_version) ||
              (github.event.inputs.run_all_versions == 'true' && matrix.rancher_version)
            }}

      - name: Set Rancher chart version
        uses: ./.github/actions/set-env-var
        with:
          key: RANCHER_CHART_VERSION
          value: |
            ${{ 
              github.event.inputs.rancher_chart_version || 
              (github.event_name == 'workflow_dispatch' && matrix.rancher_chart_version) ||
              (github.event.inputs.run_all_versions == 'true' && matrix.rancher_chart_version)
            }}

      - name: Set Rancher repo
        uses: ./.github/actions/set-rancher-repo
        with:
          rancher-version: ${{ env.RANCHER_VERSION }}
          fallback-repo: ${{ secrets.RANCHER_REPO }}

      - name: Retrieve and set ECR password
        id: get-ecr-password
        uses: ./.github/actions/get-ecr-password

      - name: Create config.yaml
        run: |
          cat > config.yaml <<EOF
          rancher:
            host: "${{ env.HOSTNAME_PREFIX }}.${{ secrets.AWS_ROUTE_53_ZONE }}"
            adminPassword: "${{ secrets.RANCHER_ADMIN_PASSWORD }}"
            insecure: true
            cleanup: true
          terraform:
            cni: "${{ secrets.CNI }}"
            defaultClusterRoleForProjectMembers: "true"
            enableNetworkPolicy: false
            provider: "${{ vars.PROVIDER_AMAZON }}"
            privateKeyPath: "${{ secrets.SSH_PRIVATE_KEY_PATH }}"
            resourcePrefix: "${{ env.HOSTNAME_PREFIX }}"
            windowsPrivateKeyPath: "${{ secrets.WINDOWS_SSH_PRIVATE_KEY_PATH }}"
            privateRegistries:
              authConfigSecretName: "${{ secrets.AUTH_CONFIG_SECRET_NAME }}"
              insecure: true
              password: "${{ env.DOCKERHUB_PASSWORD }}"
              username: "${{ env.DOCKERHUB_USERNAME }}"
            awsCredentials:
              awsAccessKey: "$AWS_ACCESS_KEY"
              awsSecretKey: "$AWS_SECRET_KEY"
            awsConfig:
              ami: "${{ secrets.AWS_AMI }}"
              awsKeyName: "${{ secrets.SSH_PRIVATE_KEY_NAME }}"
              awsInstanceType: "${{ vars.AWS_INSTANCE_TYPE }}"
              awsVolumeType: "${{ vars.AWS_VOLUME_TYPE }}"
              region: "${{ secrets.AWS_REGION }}"
              awsSecurityGroups: [${{ matrix.security_groups }}]
              awsSecurityGroupNames: [${{ matrix.security_group_names }}]
              awsSubnetID: "${{ secrets.AWS_SUBNET_ID }}"
              awsVpcID: "${{ secrets.AWS_VPC_ID }}"
              awsZoneLetter: "${{ vars.AWS_ZONE_LETTER }}"
              awsRootSize: ${{ vars.AWS_ROOT_SIZE }}
              registryRootSize: ${{ vars.AWS_ROOT_SIZE_REGISTRY}}
              awsRoute53Zone: "${{ secrets.AWS_ROUTE_53_ZONE }}"
              awsUser: "${{ secrets.AWS_USER }}"
              sshConnectionType: "${{ vars.SSH_CONNECTION_TYPE }}" 
              timeout: "${{ vars.TIMEOUT }}"
              ipAddressType: "${{ vars.IP_ADDRESS_TYPE }}"
              loadBalancerType: "${{ vars.LOAD_BALANCER_TYPE }}"
              targetType: "${{ vars.TARGET_TYPE }}"
            standalone:
              bootstrapPassword: "${{ secrets.RANCHER_ADMIN_PASSWORD }}"
              certManagerVersion: "${{ vars.CERT_MANAGER_VERSION }}"
              certType: "${{ vars.CERT_TYPE }}"
              chartVersion: "${{ env.RANCHER_CHART_VERSION }}"
              osUser: "${{ secrets.OS_USER }}"
              osGroup: "${{ secrets.OS_GROUP }}"
              rancherAgentImage: "${{ env.RANCHER_AGENT_IMAGE }}"
              rancherChartRepository: "${{ secrets.RANCHER_HELM_CHART_URL }}"
              rancherHostname: "${{ env.HOSTNAME_PREFIX }}.${{ secrets.AWS_ROUTE_53_ZONE }}"
              rancherImage: "${{ secrets.RANCHER_IMAGE }}"
              rancherTagVersion: "${{ env.RANCHER_VERSION }}"
              registryUsername: "${{ secrets.PRIVATE_REGISTRY_USERNAME }}"
              registryPassword: "${{ secrets.PRIVATE_REGISTRY_PASSWORD }}"
              repo: "${{ env.RANCHER_REPO }}"
              rke2Version: "${{ matrix.rke2_version }}"
            standaloneRegistry:
              assetsPath: "${{ secrets.ASSETS_PATH }}"
              registryName: "${{ secrets.REGISTRY_NAME }}"
              registryPassword: "${{ secrets.REGISTRY_PASSWORD }}"
              registryUsername: "${{ secrets.REGISTRY_USERNAME }}"
              ecrUsername: "${{ vars.ECR_USERNAME }}"
              ecrPassword: "${{ steps.get-ecr-password.outputs.password }}"
              ecrURI: "${{ secrets.ECR_URI }}"
          terratest:
            pathToRepo: "${{ secrets.PATH_TO_REPO }}"
          EOF

      - name: Export CATTLE_TEST_CONFIG
        run: echo "CATTLE_TEST_CONFIG=${{ github.workspace }}/config.yaml" >> $GITHUB_ENV
        shell: bash

      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version-file: "./go.mod"

      - name: Build Packages
        run: ./.github/scripts/build-packages.sh

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "${{ vars.TERRAFORM_VERSION }}"
          terraform_wrapper: false

      - name: Setup Rancher2 Provider if RC is present
        if: contains(env.RANCHER2_PROVIDER_VERSION, '-rc')
        run: /home/runner/${{ secrets.PATH_TO_REPO }}/scripts/setup-provider.sh rancher2 v${{ env.RANCHER2_PROVIDER_VERSION }}
        shell: bash

      - name: Run Registry Test Suite
        uses: ./.github/actions/run-test-suite
        with:
          package: ${{ env.PACKAGE }}
          path-to-repo: ${{ secrets.PATH_TO_REPO }}
          test-suite: ${{ env.TEST_SUITE }}
          timeout: ${{ env.SUITE_TIMEOUT }}

      - name: Reporting Results to Qase
        if: always()
        uses: ./.github/actions/report-to-qase
        with:
          qase-test-run-id: ${{ matrix.qase_id }}
          qase-automation-token: ${{ secrets.QASE_TOKEN }}

      - name: Refresh AWS credentials
        if: always()
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.TFP_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Revoke Runner IP
        if: always()
        uses: ./.github/actions/revoke-runner-ip
        with:
          prefix-list-id: ${{ env.PREFIX_LIST_ID }}
          region: "${{ secrets.AWS_REGION }}"

  report-to-slack:
    needs: registry-tests
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Reporting Results to Slack
        uses: ./.github/actions/report-to-slack
        with:
          job-status: ${{ needs.registry-tests.outputs.job-status }}
          slack-channel: ${{ secrets.SLACK_CHANNEL }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}