---
name: Verify Changes

on:
  pull_request:
    branches:
      - main

jobs:
  verify-changes:
    name: golang-ci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'

      - name: Go Version
        run: go version

      - name: Generate Golang
        run: |
          export PATH=$PATH:/home/runner/go/bin/
      
      - name: Verify Go Mod
        run: ./.github/scripts/check-go-mod.sh

      - name: Build Packages
        run: ./.github/scripts/build-packages.sh

      - name: Golangci Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.7.2
          skip-cache: true